add_newline = true
format = '''
$container$directory$git_branch$git_commit$git_state$git_metrics$git_status$cmd_duration
$character
'''

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'

[directory]
style = 'bold blue'
truncation_length = 3
fish_style_pwd_dir_length = 1

[cmd_duration]
min_time = 5000
format = '[$duration](yellow)'

[git_branch]
format = '[\($branch\)]($style) '

[container]
format = '[\[docker\]]($style) '
