# https://wiki.archlinux.org/title/XDG_Base_Directory
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_RUNTIME_DIR="$HOME/.cache"
export LANG='en_US.UTF-8'
export LC_ALL=$LANG
export PAGER='less'
export EDITOR='nvim'
export VISUAL='nvim'

# XDG
source "$XDG_CONFIG_HOME/zsh/xdg"

# vim: ft=zsh
